package com.shumkar.helpdesksystem.ticket.entity.type;

public enum TicketActivityType {
	TICKET_CREATED,
	STATUS_CHANGED,
	PRIORITY_CHANGED,
	CATEGORY_CHANGED,
	ASSIGNED,
	REASSIGNED,
	UNASSIGNED,
	COMMENT_ADDED,
	COMMENT_EDITED,
	SLA_CHANGED,
	FIRST_RESPONSE_RECORDED,
	RESOLVED,
	REOPENED,
	CLOSED
}